[package]
name = "async-utf8-decoder"
version = "0.1.0"
authors = ["Alisue <lambdalisue@hashnote.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
